#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

# We need to disable the partition manager to avoid conflicts within multicore SoCs
# that enable it by default, such as the nRF5340 and nRF54L15.
# For these SoCs, we don't add the second image to the partition manager domains.
# Since the CoreMark sample works correctly without the partition manager,
# we can disable it for all cores.
SB_CONFIG_PARTITION_MANAGER=n
